// ============================================================================
// datos.js
// Datos de ejemplo para la vista previa de los módulos: 10 registros por
// entidad, en consonancia con database/seeds.sql. Cuando la aplicación se
// conecte a la base de datos real, este archivo se sustituirá por consultas.
// ============================================================================

export const TABLAS = {
  clientes: {
    columnas: [
      { etiqueta: 'Nombre', clave: 'nombre' },
      { etiqueta: 'CIF / NIF', clave: 'cif' },
      { etiqueta: 'Teléfono', clave: 'telefono' },
      { etiqueta: 'Email', clave: 'email' },
      { etiqueta: 'Dirección', clave: 'direccion' },
    ],
    filas: [
      {
        nombre: 'Cartonajes del Sur S.L.',
        cif: 'B41000001',
        telefono: '954 100 001',
        email: 'pedidos@cartonajesdelsur.es',
        direccion: 'Pol. Ind. La Negrilla, Sevilla',
      },
      {
        nombre: 'Embalajes Levante S.A.',
        cif: 'A03000002',
        telefono: '963 200 002',
        email: 'info@embalajeslevante.com',
        direccion: 'C/ Industria 12, Valencia',
      },
      {
        nombre: 'Cajas y Envases Norte',
        cif: 'B48000003',
        telefono: '944 300 003',
        email: 'ventas@cajasnorte.es',
        direccion: 'Barrio Elorrieta, Bilbao',
      },
      {
        nombre: 'Distribuciones Ortega',
        cif: 'B28000004',
        telefono: '915 400 004',
        email: 'contacto@distortega.com',
        direccion: 'Av. de Córdoba 45, Madrid',
      },
      {
        nombre: 'Papelera del Ebro',
        cif: 'B50000005',
        telefono: '976 500 005',
        email: 'admin@papeleraelebro.com',
        direccion: 'Ctra. de Logroño 8, Zaragoza',
      },
      {
        nombre: 'Gráficas Manchegas',
        cif: 'B13000006',
        telefono: '926 600 006',
        email: 'hola@graficasmanchegas.es',
        direccion: 'Pol. Ind. Larache, Ciudad Real',
      },
      {
        nombre: 'Logística Cánovas',
        cif: 'B08000007',
        telefono: '933 700 007',
        email: 'compras@canovaslog.es',
        direccion: 'Zona Franca, Barcelona',
      },
      {
        nombre: 'Frutas del Segura',
        cif: 'B30000008',
        telefono: '968 800 008',
        email: 'frutas@delsegura.com',
        direccion: 'C/ Mayor 3, Murcia',
      },
      {
        nombre: 'Vinos de la Ribera',
        cif: 'B26000009',
        telefono: '941 900 009',
        email: 'bodega@vinosribera.es',
        direccion: 'Camino de la Bodega, Logroño',
      },
      {
        nombre: 'Farmacias Unidas',
        cif: 'B29000010',
        telefono: '952 100 010',
        email: 'central@farmaciasunidas.com',
        direccion: 'Av. Andalucía 20, Málaga',
      },
    ],
  },

  proveedores: {
    columnas: [
      { etiqueta: 'Nombre', clave: 'nombre' },
      { etiqueta: 'CIF / NIF', clave: 'cif' },
      { etiqueta: 'Material', clave: 'material' },
      { etiqueta: 'Teléfono', clave: 'telefono' },
      { etiqueta: 'Email', clave: 'email' },
    ],
    filas: [
      {
        nombre: 'Cartonajes Reunidos',
        cif: 'A41010001',
        material: 'Cartón ondulado',
        telefono: '954 111 001',
        email: 'ventas@cartonajesreunidos.es',
      },
      {
        nombre: 'Tintas Flexo Ibérica',
        cif: 'B46010002',
        material: 'Tinta flexográfica',
        telefono: '963 222 002',
        email: 'info@tintasflexo.com',
      },
      {
        nombre: 'Planchas y Clichés',
        cif: 'B08010003',
        material: 'Planchas de cliché',
        telefono: '933 333 003',
        email: 'pedidos@planchasycliches.es',
      },
      {
        nombre: 'Papelera Mediterránea',
        cif: 'A03010004',
        material: 'Papel kraft',
        telefono: '965 444 004',
        email: 'papel@mediterranea.com',
      },
      {
        nombre: 'Químicos del Ebro',
        cif: 'B50010005',
        material: 'Colas y adhesivos',
        telefono: '976 555 005',
        email: 'quimicos@delEbro.es',
      },
      {
        nombre: 'Troqueles del Norte',
        cif: 'B48010006',
        material: 'Troqueles de corte',
        telefono: '944 666 006',
        email: 'troqueles@norte.com',
      },
      {
        nombre: 'Films y Laminados',
        cif: 'A28010007',
        material: 'Film estirable',
        telefono: '915 777 007',
        email: 'films@laminados.es',
      },
      {
        nombre: 'Tintas Acuosas Sur',
        cif: 'B41010008',
        material: 'Tinta al agua',
        telefono: '954 888 008',
        email: 'acuosas@sur.es',
      },
      {
        nombre: 'Embalajes Reciclados',
        cif: 'B30010009',
        material: 'Cartón reciclado',
        telefono: '968 999 009',
        email: 'reciclados@embalajes.com',
      },
      {
        nombre: 'Rodillos Flexográficos',
        cif: 'A13010010',
        material: 'Rodillos anilox',
        telefono: '926 101 010',
        email: 'rodillos@flexo.es',
      },
    ],
  },

  empleados: {
    columnas: [
      { etiqueta: 'Nombre', clave: 'nombre' },
      { etiqueta: 'Puesto', clave: 'puesto' },
      { etiqueta: 'Turno', clave: 'turno' },
      { etiqueta: 'Nómina', clave: 'nomina', tipo: 'moneda' },
      { etiqueta: 'Fecha de alta', clave: 'fecha_alta', tipo: 'fecha' },
    ],
    filas: [
      {
        nombre: 'Antonio García',
        puesto: 'Troquelador',
        turno: 'Mañana',
        nomina: 1850,
        fecha_alta: '2018-03-12',
      },
      {
        nombre: 'María López',
        puesto: 'Impresora',
        turno: 'Tarde',
        nomina: 1920,
        fecha_alta: '2019-07-01',
      },
      {
        nombre: 'José Fernández',
        puesto: 'Operario de montaje',
        turno: 'Mañana',
        nomina: 1600,
        fecha_alta: '2020-01-15',
      },
      {
        nombre: 'Carmen Ruiz',
        puesto: 'Control de calidad',
        turno: 'Mañana',
        nomina: 1750,
        fecha_alta: '2017-09-20',
      },
      {
        nombre: 'Pedro Sánchez',
        puesto: 'Carretillero',
        turno: 'Noche',
        nomina: 1680,
        fecha_alta: '2021-04-05',
      },
      {
        nombre: 'Lucía Díaz',
        puesto: 'Administrativa',
        turno: 'Mañana',
        nomina: 1580,
        fecha_alta: '2016-11-30',
      },
      {
        nombre: 'Javier Moreno',
        puesto: 'Mecánico',
        turno: 'Tarde',
        nomina: 2000,
        fecha_alta: '2015-02-10',
      },
      {
        nombre: 'Elena Castro',
        puesto: 'Diseñadora de troqueles',
        turno: 'Mañana',
        nomina: 2100,
        fecha_alta: '2019-05-22',
      },
      {
        nombre: 'Raúl Ortega',
        puesto: 'Encargado de planta',
        turno: 'Mañana',
        nomina: 2250,
        fecha_alta: '2014-08-18',
      },
      {
        nombre: 'Marta Gil',
        puesto: 'Comercial',
        turno: 'Mañana',
        nomina: 1900,
        fecha_alta: '2022-02-14',
      },
    ],
  },

  troqueles: {
    columnas: [
      { etiqueta: 'Código', clave: 'codigo' },
      { etiqueta: 'Tipo', clave: 'tipo' },
      { etiqueta: 'Dimensiones', clave: 'dimensiones' },
      { etiqueta: 'Estado', clave: 'estado', tipo: 'estado' },
      { etiqueta: 'Ubicación', clave: 'ubicacion' },
    ],
    filas: [
      {
        codigo: 'TRQ-001',
        tipo: 'Troquel plano',
        dimensiones: '600x400 mm',
        estado: 'Disponible',
        ubicacion: 'Estantería A1',
      },
      {
        codigo: 'TRQ-002',
        tipo: 'Troquel rotativo',
        dimensiones: '800x600 mm',
        estado: 'En uso',
        ubicacion: 'Línea 2',
      },
      {
        codigo: 'TRQ-003',
        tipo: 'Troquel plano',
        dimensiones: '500x350 mm',
        estado: 'Mantenimiento',
        ubicacion: 'Taller',
      },
      {
        codigo: 'TRQ-004',
        tipo: 'Troquel rotativo',
        dimensiones: '1000x700 mm',
        estado: 'Disponible',
        ubicacion: 'Estantería A2',
      },
      {
        codigo: 'TRQ-005',
        tipo: 'Troquel plano',
        dimensiones: '450x300 mm',
        estado: 'Disponible',
        ubicacion: 'Estantería B1',
      },
      {
        codigo: 'TRQ-006',
        tipo: 'Troquel especial',
        dimensiones: '750x550 mm',
        estado: 'En uso',
        ubicacion: 'Línea 1',
      },
      {
        codigo: 'TRQ-007',
        tipo: 'Troquel plano',
        dimensiones: '620x420 mm',
        estado: 'Disponible',
        ubicacion: 'Estantería B2',
      },
      {
        codigo: 'TRQ-008',
        tipo: 'Troquel rotativo',
        dimensiones: '900x650 mm',
        estado: 'Mantenimiento',
        ubicacion: 'Taller',
      },
      {
        codigo: 'TRQ-009',
        tipo: 'Troquel plano',
        dimensiones: '550x380 mm',
        estado: 'Disponible',
        ubicacion: 'Estantería C1',
      },
      {
        codigo: 'TRQ-010',
        tipo: 'Troquel especial',
        dimensiones: '680x480 mm',
        estado: 'En uso',
        ubicacion: 'Línea 3',
      },
    ],
  },

  articulos: {
    columnas: [
      { etiqueta: 'Referencia', clave: 'referencia' },
      { etiqueta: 'Descripción', clave: 'descripcion' },
      { etiqueta: 'Medidas', clave: 'medidas' },
      { etiqueta: 'Precio', clave: 'precio', tipo: 'moneda' },
      { etiqueta: 'Material', clave: 'material' },
    ],
    filas: [
      {
        referencia: 'ART-001',
        descripcion: 'Caja americana estándar',
        medidas: '400x300x200 mm',
        precio: 1.25,
        material: 'Cartón ondulado BC',
      },
      {
        referencia: 'ART-002',
        descripcion: 'Caja con tapa',
        medidas: '350x250x150 mm',
        precio: 0.98,
        material: 'Cartón ondulado C',
      },
      {
        referencia: 'ART-003',
        descripcion: 'Estuche con cierre',
        medidas: '200x150x80 mm',
        precio: 0.65,
        material: 'Cartoncillo',
      },
      {
        referencia: 'ART-004',
        descripcion: 'Bandeja expositora',
        medidas: '600x400x120 mm',
        precio: 2.1,
        material: 'Cartón ondulado B',
      },
      {
        referencia: 'ART-005',
        descripcion: 'Embalaje postal',
        medidas: '300x200x100 mm',
        precio: 0.45,
        material: 'Cartón reciclado',
      },
      {
        referencia: 'ART-006',
        descripcion: 'Caja archivo',
        medidas: '330x260x250 mm',
        precio: 1.75,
        material: 'Cartón ondulado BC',
      },
      {
        referencia: 'ART-007',
        descripcion: 'Separadores de cartón',
        medidas: '400x300 mm',
        precio: 0.22,
        material: 'Cartón compacto',
      },
      {
        referencia: 'ART-008',
        descripcion: 'Caja para botellas',
        medidas: '350x180x280 mm',
        precio: 1.6,
        material: 'Cartón ondulado C',
      },
      {
        referencia: 'ART-009',
        descripcion: 'Blíster de cartón',
        medidas: '150x120x50 mm',
        precio: 0.55,
        material: 'Cartoncillo',
      },
      {
        referencia: 'ART-010',
        descripcion: 'Palet de cartón',
        medidas: '1200x800 mm',
        precio: 5.4,
        material: 'Cartón nido de abeja',
      },
    ],
  },

  cliches: {
    columnas: [
      { etiqueta: 'Código', clave: 'codigo' },
      { etiqueta: 'Diseño', clave: 'diseno' },
      { etiqueta: 'Tintas', clave: 'tintas' },
      { etiqueta: 'Estado', clave: 'estado', tipo: 'estado' },
      { etiqueta: 'Cliente', clave: 'cliente' },
    ],
    filas: [
      {
        codigo: 'CL-001',
        diseno: 'Logotipo Cartonajes del Sur',
        tintas: '2 tintas',
        estado: 'Disponible',
        cliente: 'Cartonajes del Sur S.L.',
      },
      {
        codigo: 'CL-002',
        diseno: 'Etiqueta Embalajes Levante',
        tintas: '3 tintas',
        estado: 'Disponible',
        cliente: 'Embalajes Levante S.A.',
      },
      {
        codigo: 'CL-003',
        diseno: 'Motivo navideño',
        tintas: '4 tintas',
        estado: 'En uso',
        cliente: 'Cajas y Envases Norte',
      },
      {
        codigo: 'CL-004',
        diseno: 'Texto legal farmacias',
        tintas: '1 tinta',
        estado: 'Disponible',
        cliente: 'Farmacias Unidas',
      },
      {
        codigo: 'CL-005',
        diseno: 'Marca Vinos de la Ribera',
        tintas: '3 tintas',
        estado: 'Disponible',
        cliente: 'Vinos de la Ribera',
      },
      {
        codigo: 'CL-006',
        diseno: 'Código de barras EAN',
        tintas: '1 tinta',
        estado: 'En uso',
        cliente: 'Distribuciones Ortega',
      },
      {
        codigo: 'CL-007',
        diseno: 'Ilustración frutas',
        tintas: '5 tintas',
        estado: 'Disponible',
        cliente: 'Frutas del Segura',
      },
      {
        codigo: 'CL-008',
        diseno: 'Sello de calidad',
        tintas: '2 tintas',
        estado: 'Mantenimiento',
        cliente: 'Papelera del Ebro',
      },
      {
        codigo: 'CL-009',
        diseno: 'Logotipo Papelera del Ebro',
        tintas: '2 tintas',
        estado: 'Disponible',
        cliente: 'Papelera del Ebro',
      },
      {
        codigo: 'CL-010',
        diseno: 'Motivo corporativo',
        tintas: '4 tintas',
        estado: 'En uso',
        cliente: 'Gráficas Manchegas',
      },
    ],
  },

  pedidos: {
    columnas: [
      { etiqueta: 'Nº pedido', clave: 'numero' },
      { etiqueta: 'Cliente', clave: 'cliente' },
      { etiqueta: 'Fecha entrega', clave: 'fecha_entrega', tipo: 'fecha' },
      { etiqueta: 'Estado', clave: 'estado', tipo: 'estado' },
      { etiqueta: 'Artículos', clave: 'articulos' },
    ],
    filas: [
      {
        numero: 'PED-2026-001',
        cliente: 'Cartonajes del Sur S.L.',
        fecha_entrega: '2026-09-20',
        estado: 'En producción',
        articulos: '2 artículos',
      },
      {
        numero: 'PED-2026-002',
        cliente: 'Embalajes Levante S.A.',
        fecha_entrega: '2026-09-25',
        estado: 'Pendiente',
        articulos: '1 artículo',
      },
      {
        numero: 'PED-2026-003',
        cliente: 'Cajas y Envases Norte',
        fecha_entrega: '2026-09-18',
        estado: 'En producción',
        articulos: '1 artículo',
      },
      {
        numero: 'PED-2026-004',
        cliente: 'Distribuciones Ortega',
        fecha_entrega: '2026-10-02',
        estado: 'Pendiente',
        articulos: '1 artículo',
      },
      {
        numero: 'PED-2026-005',
        cliente: 'Papelera del Ebro',
        fecha_entrega: '2026-09-30',
        estado: 'Confirmado',
        articulos: '1 artículo',
      },
      {
        numero: 'PED-2026-006',
        cliente: 'Gráficas Manchegas',
        fecha_entrega: '2026-10-05',
        estado: 'Pendiente',
        articulos: '1 artículo',
      },
      {
        numero: 'PED-2026-007',
        cliente: 'Logística Cánovas',
        fecha_entrega: '2026-09-22',
        estado: 'En producción',
        articulos: '1 artículo',
      },
      {
        numero: 'PED-2026-008',
        cliente: 'Frutas del Segura',
        fecha_entrega: '2026-09-28',
        estado: 'Confirmado',
        articulos: '1 artículo',
      },
      {
        numero: 'PED-2026-009',
        cliente: 'Vinos de la Ribera',
        fecha_entrega: '2026-10-08',
        estado: 'Pendiente',
        articulos: '1 artículo',
      },
      {
        numero: 'PED-2026-010',
        cliente: 'Farmacias Unidas',
        fecha_entrega: '2026-09-26',
        estado: 'En producción',
        articulos: '2 artículos',
      },
    ],
  },
};
